#	$NetBSD: Makefile,v 1.3 2018/05/01 19:59:47 christos Exp $

.include <bsd.hostinit.mk>

HOST_BUILD=
NO_LLVM_DEVELOPER=	yes

.include "${.PARSEDIR}/../llvm/Makefile.inc"

.include "${LLVM_TOPLEVEL}/lib/Makefile"
